version: "3.5"
services:
  web:
    container_name: chw-supervision
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9900:3000
    environment:
      - NODE_ENV=production
    networks:
      - custom
networks:
  custom:
    driver: bridge
