export const kenyaCounties = [
  { value: 'Bomet', label: 'Bomet' },
  { value: 'Bungoma', label: 'Bungoma' },
  { value: 'Busia', label: 'Busia' },
  { value: 'Elgeyo Marakwet', label: 'Elgeyo Marakwet' },
  { value: 'Embu', label: 'Embu' },
  { value: 'Garissa', label: 'Garissa' },
  { value: 'Homa Bay', label: 'Homa Bay' },
  { value: 'Isiolo', label: 'Isiolo' },
  { value: 'Kajiado', label: 'Kajiado' },
  { value: 'Kakamega', label: 'Kakamega' },
  { value: 'Kericho', label: 'Kericho' },
  { value: 'Kiambu', label: 'Kiambu' },
  { value: 'Kilifi', label: 'Kilifi' },
  { value: 'Kirinyaga', label: 'Kirinyaga' },
  { value: 'Kisii', label: 'Kisii' },
  { value: 'Kisumu', label: 'Kisumu' },
  { value: 'Kitui', label: 'Kitui' },
  { value: 'Kwale', label: 'Kwale' },
  { value: 'Laikipia', label: 'Laikipia' },
  { value: 'Lamu', label: 'Lamu' },
  { value: 'Machakos', label: 'Machakos' },
  { value: 'Makueni', label: 'Makueni' },
  { value: 'Mandera', label: 'Mandera' },
  { value: 'Marsabit', label: 'Marsabit' },
  { value: 'Meru', label: 'Meru' },
  { value: 'Migori', label: 'Migori' },
  { value: 'Mombasa', label: 'Mombasa' },
  { value: "Murang'a", label: "Murang'a" },
  { value: 'Nairobi', label: 'Nairobi' },
  { value: 'Nakuru', label: 'Nakuru' },
  { value: 'Nandi', label: 'Nandi' },
  { value: 'Narok', label: 'Narok' },
  { value: 'Nyamira', label: 'Nyamira' },
  { value: 'Nyandarua', label: 'Nyandarua' },
  { value: 'Nyanza', label: 'Nyanza' },
  { value: 'Samburu', label: 'Samburu' },
  { value: 'Siaya', label: 'Siaya' },
  { value: 'Taita Taveta', label: 'Taita Taveta' },
  { value: 'Tana River', label: 'Tana River' },
  { value: 'Tharaka Nithi', label: 'Tharaka Nithi' },
  { value: 'Trans Nzoia', label: 'Trans Nzoia' },
  { value: 'Uasin Gishu', label: 'Uasin Gishu' },
  { value: 'Vihiga', label: 'Vihiga' },
  { value: 'Wajir', label: 'Wajir' },
  { value: 'West Pokot', label: 'West Pokot' },
];
export const kenyaSubcounties = {
  Bomet: [
    { value: 'Bomet Central', label: 'Bomet Central' },
    { value: 'Bomet East', label: 'Bomet East' },
    { value: 'Bomet West', label: 'Bomet West' },
    { value: 'Chepalungu', label: 'Chepalungu' },
    { value: 'Konoin', label: 'Konoin' },
  ],
  Bungoma: [
    { value: 'Bungoma Central', label: 'Bungoma Central' },
    { value: 'Bumula', label: 'Bumula' },
    { value: 'Kabuchai', label: 'Kabuchai' },
    { value: 'Kanduyi', label: 'Kanduyi' },
    { value: 'Mt. Elgon', label: 'Mt. Elgon' },
    { value: 'Sirisia', label: 'Sirisia' },
  ],
  Busia: [
    { value: 'Bunyala', label: 'Bunyala' },
    { value: 'Butula', label: 'Butula' },
    { value: 'Funyula', label: 'Funyula' },
    { value: 'Nambale', label: 'Nambale' },
    { value: 'Teso North', label: 'Teso North' },
    { value: 'Teso South', label: 'Teso South' },
  ],
  'Elgeyo Marakwet': [
    { value: 'Emgwen', label: 'Emgwen' },
    { value: 'Keiyo North', label: 'Keiyo North' },
    { value: 'Keiyo South', label: 'Keiyo South' },
    { value: 'Marakwet East', label: 'Marakwet East' },
    { value: 'Marakwet West', label: 'Marakwet West' },
  ],
  Embu: [
    { value: 'Embu North', label: 'Embu North' },
    { value: 'Embu West', label: 'Embu West' },
    { value: 'Mbeere North', label: 'Mbeere North' },
    { value: 'Mbeere South', label: 'Mbeere South' },
  ],
  Garissa: [
    { value: 'Balambala', label: 'Balambala' },
    { value: 'Dadaab', label: 'Dadaab' },
    { value: 'Garissa Township', label: 'Garissa Township' },
    { value: 'Ijara', label: 'Ijara' },
    { value: 'Lagdera', label: 'Lagdera' },
  ],
  'Homa Bay': [
    { value: 'Homa Bay Town', label: 'Homa Bay Town' },
    { value: 'Kissi', label: 'Kissi' },
    { value: 'Kondele', label: 'Kondele' },
    { value: 'Rachuonyo North', label: 'Rachuonyo North' },
    { value: 'Rachuonyo South', label: 'Rachuonyo South' },
  ],
  Isiolo: [
    { value: 'Isiolo Central', label: 'Isiolo Central' },
    { value: 'Isiolo North', label: 'Isiolo North' },
    { value: 'Isiolo South', label: 'Isiolo South' },
  ],
  Kajiado: [
    { value: 'Kajiado East', label: 'Kajiado East' },
    { value: 'Kajiado North', label: 'Kajiado North' },
    { value: 'Kajiado South', label: 'Kajiado South' },
    { value: 'Kajiado West', label: 'Kajiado West' },
  ],
  Kakamega: [
    { value: 'Bunyala', label: 'Bunyala' },
    { value: 'Butere', label: 'Butere' },
    { value: 'Kakamega Central', label: 'Kakamega Central' },
    { value: 'Kakamega North', label: 'Kakamega North' },
    { value: 'Kakamega South', label: 'Kakamega South' },
    { value: 'Lurambi', label: 'Lurambi' },
    { value: 'Mumias East', label: 'Mumias East' },
    { value: 'Mumias West', label: 'Mumias West' },
    { value: 'Navakholo', label: 'Navakholo' },
  ],
  Kericho: [
    { value: 'Ainamoi', label: 'Ainamoi' },
    { value: 'Buret', label: 'Buret' },
    { value: 'Kipkelion East', label: 'Kipkelion East' },
    { value: 'Kipkelion West', label: 'Kipkelion West' },
    { value: 'Sigowet/Soin', label: 'Sigowet/Soin' },
  ],
  Kiambu: [
    { value: 'Gatundu North', label: 'Gatundu North' },
    { value: 'Gatundu South', label: 'Gatundu South' },
    { value: 'Juja', label: 'Juja' },
    { value: 'Kikuyu', label: 'Kikuyu' },
    { value: 'Kiambu Town', label: 'Kiambu Town' },
    { value: 'Thika Town', label: 'Thika Town' },
  ],
  Kilifi: [
    { value: 'Kilifi North', label: 'Kilifi North' },
    { value: 'Kilifi South', label: 'Kilifi South' },
    { value: 'Malindi', label: 'Malindi' },
    { value: 'Magarini', label: 'Magarini' },
    { value: 'Kaloleni', label: 'Kaloleni' },
  ],
  Kirinyaga: [
    { value: 'Kirinyaga Central', label: 'Kirinyaga Central' },
    { value: 'Kirinyaga East', label: 'Kirinyaga East' },
    { value: 'Kirinyaga West', label: 'Kirinyaga West' },
  ],
  Kisii: [
    { value: 'Bobasi', label: 'Bobasi' },
    { value: 'Bomachoge', label: 'Bomachoge' },
    { value: 'Kenyenya', label: 'Kenyenya' },
    { value: 'Kitutu Chache', label: 'Kitutu Chache' },
    { value: 'Marani', label: 'Marani' },
    { value: 'Mosocho', label: 'Mosocho' },
    { value: 'Nyaribari Chache', label: 'Nyaribari Chache' },
    { value: 'Nyaribari Masaba', label: 'Nyaribari Masaba' },
  ],
  Kisumu: [
    { value: 'Kisumu Central', label: 'Kisumu Central' },
    { value: 'Kisumu East', label: 'Kisumu East' },
    { value: 'Kisumu West', label: 'Kisumu West' },
    { value: 'Nyando', label: 'Nyando' },
    { value: 'Muhoroni', label: 'Muhoroni' },
  ],
  Kitui: [
    { value: 'Kitui Central', label: 'Kitui Central' },
    { value: 'Kitui East', label: 'Kitui East' },
    { value: 'Kitui South', label: 'Kitui South' },
    { value: 'Kitui West', label: 'Kitui West' },
    { value: 'Mwingi Central', label: 'Mwingi Central' },
    { value: 'Mwingi North', label: 'Mwingi North' },
    { value: 'Mwingi West', label: 'Mwingi West' },
  ],
  Kwale: [
    { value: 'Lungalunga', label: 'Lungalunga' },
    { value: 'Matuga', label: 'Matuga' },
    { value: 'Msambweni', label: 'Msambweni' },
    { value: 'Kinango', label: 'Kinango' },
  ],
  Laikipia: [
    { value: 'Laikipia East', label: 'Laikipia East' },
    { value: 'Laikipia North', label: 'Laikipia North' },
    { value: 'Laikipia West', label: 'Laikipia West' },
  ],
  Lamu: [
    { value: 'Lamu East', label: 'Lamu East' },
    { value: 'Lamu West', label: 'Lamu West' },
  ],
  Machakos: [
    { value: 'Machakos Town', label: 'Machakos Town' },
    { value: 'Masinga', label: 'Masinga' },
    { value: 'Mavoko', label: 'Mavoko' },
    { value: 'Kangundo', label: 'Kangundo' },
    { value: 'Matungulu', label: 'Matungulu' },
    { value: 'Yatta', label: 'Yatta' },
  ],
  Makueni: [
    { value: 'Makueni', label: 'Makueni' },
    { value: 'Kangundo', label: 'Kangundo' },
    { value: 'Matungulu', label: 'Matungulu' },
    { value: 'Mbooni', label: 'Mbooni' },
  ],
  Mandera: [
    { value: 'Banissa', label: 'Banissa' },
    { value: 'Mandera East', label: 'Mandera East' },
    { value: 'Mandera North', label: 'Mandera North' },
    { value: 'Mandera South', label: 'Mandera South' },
    { value: 'Lafey', label: 'Lafey' },
  ],
  Marsabit: [
    { value: 'Laisamis', label: 'Laisamis' },
    { value: 'Marsabit', label: 'Marsabit' },
    { value: 'North Horr', label: 'North Horr' },
    { value: 'Saku', label: 'Saku' },
  ],
  Meru: [
    { value: 'Imenti North', label: 'Imenti North' },
    { value: 'Imenti South', label: 'Imenti South' },
    { value: 'Tigania East', label: 'Tigania East' },
    { value: 'Tigania West', label: 'Tigania West' },
    { value: 'Buuri', label: 'Buuri' },
    { value: 'Central Imenti', label: 'Central Imenti' },
  ],
  Migori: [
    { value: 'Abwao', label: 'Abwao' },
    { value: 'Bomachoge', label: 'Bomachoge' },
    { value: 'Kuria East', label: 'Kuria East' },
    { value: 'Kuria West', label: 'Kuria West' },
    { value: 'Migori Town', label: 'Migori Town' },
    { value: 'Rongo', label: 'Rongo' },
    { value: 'Suna East', label: 'Suna East' },
    { value: 'Suna West', label: 'Suna West' },
  ],
  Mombasa: [
    { value: 'Mvita', label: 'Mvita' },
    { value: 'Kisauni', label: 'Kisauni' },
    { value: 'Nyali', label: 'Nyali' },
    { value: 'Jomvu', label: 'Jomvu' },
    { value: 'Likoni', label: 'Likoni' },
  ],
  "Murang'a": [
    { value: 'Kangema', label: 'Kangema' },
    { value: 'Kiharu', label: 'Kiharu' },
    { value: 'Kandara', label: 'Kandara' },
    { value: 'Mathioya', label: 'Mathioya' },
    { value: "Murang'a Town", label: "Murang'a Town" },
  ],
  Nairobi: [
    { value: 'Starehe', label: 'Starehe' },
    { value: 'Westlands', label: 'Westlands' },
    { value: "Lang'ata", label: "Lang'ata" },
    { value: 'Kamukunji', label: 'Kamukunji' },
    { value: 'Makadara', label: 'Makadara' },
    { value: 'Embakasi', label: 'Embakasi' },
  ],
  Nakuru: [
    { value: 'Nakuru Town East', label: 'Nakuru Town East' },
    { value: 'Nakuru Town West', label: 'Nakuru Town West' },
    { value: 'Bahati', label: 'Bahati' },
    { value: 'Gilgil', label: 'Gilgil' },
    { value: 'Kuresoi North', label: 'Kuresoi North' },
    { value: 'Kuresoi South', label: 'Kuresoi South' },
    { value: 'Molo', label: 'Molo' },
    { value: 'Njoro', label: 'Njoro' },
    { value: 'Rongai', label: 'Rongai' },
    { value: 'Subukia', label: 'Subukia' },
  ],
  Nandi: [
    { value: 'Nandi Hills', label: 'Nandi Hills' },
    { value: 'Chesumei', label: 'Chesumei' },
    { value: 'Emgwen', label: 'Emgwen' },
    { value: 'Ainabkoi', label: 'Ainabkoi' },
  ],
  Narok: [
    { value: 'Narok East', label: 'Narok East' },
    { value: 'Narok North', label: 'Narok North' },
    { value: 'Narok South', label: 'Narok South' },
    { value: 'Narok West', label: 'Narok West' },
    { value: 'Trans Mara East', label: 'Trans Mara East' },
    { value: 'Trans Mara West', label: 'Trans Mara West' },
  ],
  Nyamira: [
    { value: 'Bobasi', label: 'Bobasi' },
    { value: 'Bomachoge', label: 'Bomachoge' },
    { value: 'Kenyenya', label: 'Kenyenya' },
    { value: 'Kitutu Chache', label: 'Kitutu Chache' },
    { value: 'Marani', label: 'Marani' },
    { value: 'Mosocho', label: 'Mosocho' },
    { value: 'Nyaribari Chache', label: 'Nyaribari Chache' },
    { value: 'Nyaribari Masaba', label: 'Nyaribari Masaba' },
  ],
  Nyandarua: [
    { value: 'Kinangop', label: 'Kinangop' },
    { value: 'Nyandarua', label: 'Nyandarua' },
    { value: 'Ol Kalou', label: 'Ol Kalou' },
    { value: 'Ndaragwa', label: 'Ndaragwa' },
  ],
  Nyanza: [
    { value: 'Kisumu', label: 'Kisumu' },
    { value: 'Homa Bay', label: 'Homa Bay' },
    { value: 'Kisii', label: 'Kisii' },
    { value: 'Migori', label: 'Migori' },
    { value: 'Siaya', label: 'Siaya' },
    { value: 'Nyamira', label: 'Nyamira' },
  ],
  Samburu: [
    { value: 'Samburu East', label: 'Samburu East' },
    { value: 'Samburu North', label: 'Samburu North' },
    { value: 'Samburu West', label: 'Samburu West' },
  ],
  Siaya: [
    { value: 'Alego Usonga', label: 'Alego Usonga' },
    { value: 'Bondo', label: 'Bondo' },
    { value: 'Gem', label: 'Gem' },
    { value: 'Rarieda', label: 'Rarieda' },
    { value: 'Ugenya', label: 'Ugenya' },
    { value: 'Ugunja', label: 'Ugunja' },
  ],
  'Taita Taveta': [
    { value: 'Taveta', label: 'Taveta' },
    { value: 'Voi', label: 'Voi' },
    { value: 'Mwatate', label: 'Mwatate' },
    { value: 'Wundanyi', label: 'Wundanyi' },
  ],
  'Tana River': [
    { value: 'Bura', label: 'Bura' },
    { value: 'Garsen', label: 'Garsen' },
    { value: 'Galole', label: 'Galole' },
    { value: 'Tana North', label: 'Tana North' },
    { value: 'Tana River', label: 'Tana River' },
  ],
  'Tharaka Nithi': [
    { value: 'Chuka', label: 'Chuka' },
    { value: 'Igembe Central', label: 'Igembe Central' },
    { value: 'Igembe North', label: 'Igembe North' },
    { value: 'Igembe South', label: 'Igembe South' },
    { value: 'Maara', label: 'Maara' },
    { value: 'Tharaka', label: 'Tharaka' },
  ],
  'Trans Nzoia': [
    { value: 'Kiminini', label: 'Kiminini' },
    { value: 'Saboti', label: 'Saboti' },
    { value: 'Trans Nzoia East', label: 'Trans Nzoia East' },
    { value: 'Trans Nzoia West', label: 'Trans Nzoia West' },
  ],
  'Uasin Gishu': [
    { value: 'Ainabkoi', label: 'Ainabkoi' },
    { value: 'Kapseret', label: 'Kapseret' },
    { value: 'Kesses', label: 'Kesses' },
    { value: 'Moiben', label: 'Moiben' },
    { value: 'Uasin Gishu', label: 'Uasin Gishu' },
  ],
  Vihiga: [
    { value: 'Emuhaya', label: 'Emuhaya' },
    { value: 'Hamisi', label: 'Hamisi' },
    { value: 'Luanda', label: 'Luanda' },
    { value: 'Sabatia', label: 'Sabatia' },
    { value: 'Vihiga', label: 'Vihiga' },
  ],
  Wajir: [
    { value: 'Wajir East', label: 'Wajir East' },
    { value: 'Wajir North', label: 'Wajir North' },
    { value: 'Wajir South', label: 'Wajir South' },
    { value: 'Wajir West', label: 'Wajir West' },
  ],
  'West Pokot': [
    { value: 'Kacheliba', label: 'Kacheliba' },
    { value: 'Kapenguria', label: 'Kapenguria' },
    { value: 'Pokot North', label: 'Pokot North' },
    { value: 'Pokot South', label: 'Pokot South' },
  ],
  // Add more counties and subcounties as needed...
};
export const kenyaChus = []